redis:
  hostname: 127.0.0.1
  port: 6379
  username: ""
  password: ""
  uri: "redis://localhost:6379"
console-name: "Console"
console-server: "N/A"
unknown-server: "N/A"
show-init-times: true
default-channel-prefix: "jelly-chats/"
chats:
  staff:
    enabled: true
    name: "Staff"
    channel: "jelly-chats/staff"
    permission: "jelly-chats.chat.staff"
    command:
      main: "staff-chat"
      aliases:
        - "s"
        - "sc"
        - "staffchat"
        - "staff"
  admin:
    enabled: true
    name: "Admin"
    channel: "jelly-chats/admin"
    permission: "jelly-chats.chat.admin"
    command:
      main: "admin-chat"
      aliases:
        - "a"
        - "ac"
        - "adminchat"
        - "admin"
messages:
  usage: "<red>Usage: /<name> <message></red>"
  chat-disabled: "<red>Sorry, that private chat is disabled.</red>"
  formatting:
    staff: "<color:#15c224>[STAFF] (<server>)</color> <color:#5fd961><author>:</color> <content>"
    admin: "<color:#ff2b39>[ADMIN] (<server>)</color> <color:#ff6973><author>:</color> <content>"
    fallback: "<color:#ff59e3>[<chat>] (<server>)</color> <color:#ffabf2><player>:</color> <content>"