redis:
  uri: "redis://localhost:6379"
console-name: "Console"
show-init-times: true
channels:
  format:
    staff: "<color:#15c224>[STAFF]</color> <color:#5fd961><author>:</color> <content>"
    admin: "<color:#ff2b39>[ADMIN]</color> <color:#ff6973><author>:</color> <content>"
commands:
  usage:
    admin: "<red>Usage: /admin-chat <message></red>"
    staff: "<red>Usage: /staff-chat <message></red>"